Algoritmo "TrianguloEquilatero"

Var
   A,B,C : inteiro

Inicio
      escreva("Digite o seu valor do lado A do triangulo: ")
      leia(A)
      escreva("Digite o seu valor do lado B do triangulo: ")
      leia(B)
      escreva("Digite o seu valor do lado C do triangulo: ")
      leia(C)
      se (A = B)e(A = C)e(B = C)entao
      escreva ("Triângulo equilátero")
      senao
      escreva ("Triângulo nao é equilátero")
      fimse
      
Fimalgoritmo